// Thin re-export so component code imports from a stable dashboard path.
// The real API surface is generated by `npx convex dev` into ../../convex/_generated/.
// If codegen has not run yet, this import will fail; that is the signal to run convex dev.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error: file is generated by `npx convex dev`; run it once before building the dashboard.
export { api } from "../../convex/_generated/api";
